In [1]:
import numpy as np

x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)

print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)

x_data.ndim =  2 , x_data.shape =  (9, 2)
t_data.ndim =  2 , t_data.shape =  (9, 1)


In [7]:
W = np.random.rand(2, 1)
b = np.random.rand(1)
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.22377714]
 [0.7419718 ]] , W.shape =  (2, 1) , b =  [0.48549435] , b.shape =  (1,)


In [3]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

def loss_func(x, t):
    delta = 1e-7 # log 무한대 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    return -np.sum( t*np.log(y+delta) + (1-t)*np.log((1-y)+delta))

In [4]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [11]:
def error_val(x, t):
    delta = 1e-7
    
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    return -np.sum( t*np.log(y+delta) + (1-t)*np.log((1-y)+delta))

def predict(x):
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    if y >= 0.5:
        result = 1
    else: 
        result = 0
        
    return y, result

In [8]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data,t_data)
    
print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b)

for step in range(10001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if(step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ", b)

Initial error value =  25.734117632230497 Initial W =  [[0.22377714]
 [0.7419718 ]] 
 , b =  [0.48549435]
step =  0 error value =  15.154520868296537 W =  [[0.02490449]
 [0.4832596 ]] , b =  [0.44828501]
step =  400 error value =  2.253329711684124 W =  [[ 0.42283451]
 [-0.08534979]] , b =  [-2.66123232]
step =  800 error value =  1.5834510284114316 W =  [[ 0.53805578]
 [-0.02560684]] , b =  [-4.28610796]
step =  1200 error value =  1.2757592485052587 W =  [[0.62479906]
 [0.00953314]] , b =  [-5.39165066]
step =  1600 error value =  1.0954923089730646 W =  [[0.69488596]
 [0.034624  ]] , b =  [-6.23874423]
step =  2000 error value =  0.9747677340604699 W =  [[0.75399542]
 [0.05463326]] , b =  [-6.9321745]
step =  2400 error value =  0.8868201544195978 W =  [[0.80526664]
 [0.07177183]] , b =  [-7.5240713]
step =  2800 error value =  0.8189645425571671 W =  [[0.85061983]
 [0.08718511]] , b =  [-8.04397375]
step =  3200 error value =  0.764400932157089 W =  [[0.89131925]
 [0.10152618]] , b

In [12]:
test_data = np.array([3, 17])
predict(test_data)

(array([0.01524952]), 0)

In [13]:
test_data = np.array([10, 4]) # (예습, 복습) = (10, 4) => Fail (0)
predict(test_data)

(array([0.6750399]), 1)

In [14]:
test_data = np.array([7, 21])
predict(test_data)

(array([0.90068426]), 1)

In [ ]:
test_data = np.array([3, 17])
predict(test_data)