In [14]:
import numpy as np
# sigmoid 함수
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [15]:
# 수치미분 함수
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [35]:

class LogicGate2:
    
    def __init__(self, gate_name, xdata, tdata):
        
        self.name = gate_name
        
        # 입력 데이터, 정답 데이터 초기화
        self.__xdata = xdata.reshape(4, 2)
        self.__tdata = tdata.reshape(4, 1)
        
        # 2층 hidden layer unit : 6개 가정, 가중치 W2, 바이어스 b2 초기화
        self.__W2 = np.random.rand(2,6) # weight, 2 x 6 matrix
        self.__b2 = np.random.rand(6)
        
        # 3층 output layer unit : 1개, 가중치 W3, 바이어스 b3 초기화
        self.__W3 = np.random.rand(6,1)
        self.__b3 = np.random.rand(1)
        
        self.__learning_rate = 1e-2
        
        print(self.name + " object is created")
        
    def feed_forward(self):
        
        delta = 1e-7
        
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2 # 은닉층의 선형회귀 값
        a2 = sigmoid(z2) # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3 # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3) # 출력층의 출력
        
        return -np.sum(self.__tdata * np.log(y + delta) + (1 - self.__tdata) * np.log((1 - y) + delta))
        
        
    def loss_val(self): # 외부 출력을 위한 손실함수(cross-entropy) 값 계산
        
        delta = 1e-7
        
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, self.__W3) + self.__b3
        y = a3 = sigmoid(z3)
        
        return -np.sum(self.__tdata * np.log(y + delta) + (1 - self.__tdata) * np.log((1 - y) + delta))
 
    def train(self):
        
        f = lambda x : self.feed_forward()
        
        print('Initial loss value = ', self.loss_val())
        
        for step in range(10001):
            
            self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
            self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
            self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
            self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)
            
            if (step % 400 == 0):
                print("step = ", step, "loss value = ", self.loss_val())
                
    def predict(self, xdata):
        
        z2 = np.dot(xdata, self.__W2) + self.__b2 # 은닉층의 선형회귀 값
        a2 = sigmoid(z2) # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3 # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3) # 출력층의 출력
        
        if y > 0.5:
            result = 1
        else:
            result = 0
            
        return y, result

In [37]:
xdata = np.array([ [0,0], [0,1], [1,0], [1,1] ])
tdata = np.array([0,0,0,1])

AND_obj = LogicGate2("AND_GATE", xdata, tdata)

AND_obj.train()

AND_GATE object is created
Initial loss value =  8.86598842701466
step =  0 loss value =  8.553596526833829
step =  400 loss value =  2.168773863241032
step =  800 loss value =  1.965907120403696
step =  1200 loss value =  1.659529674471039
step =  1600 loss value =  1.307835778085088
step =  2000 loss value =  0.9909748689680493
step =  2400 loss value =  0.7371213828610498
step =  2800 loss value =  0.550005031350226
step =  3200 loss value =  0.4182345840932329
step =  3600 loss value =  0.32631094646303527
step =  4000 loss value =  0.26136845281046084
step =  4400 loss value =  0.2144446085035564
step =  4800 loss value =  0.17967388190893124
step =  5200 loss value =  0.1532668805811156
step =  5600 loss value =  0.1327527559211782
step =  6000 loss value =  0.11649005226299271
step =  6400 loss value =  0.1033640220972527
step =  6800 loss value =  0.09260038613009244
step =  7200 loss value =  0.08364956799091963
step =  7600 loss value =  0.07611349610737482
step =  8000 loss 

In [38]:
print(AND_obj.name, "\n")

test_data = np.array([[0,0], [0,1], [1,0], [1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = AND_obj.predict(input_data)
    print(input_data, " = ", logical_val, "\n")

for data in test_data:
    print(AND_obj.predict(data))

AND_GATE 

[0 0]  =  0 

[0 1]  =  0 

[1 0]  =  0 

[1 1]  =  1 

(array([0.00030379]), 0)
(array([0.01199231]), 0)
(array([0.01267523]), 0)
(array([0.97711009]), 1)


In [40]:
xdata = np.array([[0,0], [0,1], [1,0], [1,1]])
tdata = np.array([0,1,1,0])

XOR_obj = LogicGate2("XOR_GATE", xdata, tdata)

XOR_obj.train()

XOR_GATE object is created
Initial loss value =  4.97469148381823
step =  0 loss value =  4.8799007346101835
step =  400 loss value =  2.7665805268478936
step =  800 loss value =  2.7638131615589336
step =  1200 loss value =  2.759726905707175
step =  1600 loss value =  2.7535046435133625
step =  2000 loss value =  2.7438963317932723
step =  2400 loss value =  2.729135479968894
step =  2800 loss value =  2.7069719901382556
step =  3200 loss value =  2.674787302724853
step =  3600 loss value =  2.6296910137314455
step =  4000 loss value =  2.5688722265199533
step =  4400 loss value =  2.490854579511729
step =  4800 loss value =  2.3972234681206235
step =  5200 loss value =  2.2925878884373554
step =  5600 loss value =  2.181987844447944
step =  6000 loss value =  2.068311046410521
step =  6400 loss value =  1.9516469371356686
step =  6800 loss value =  1.830084332639232
step =  7200 loss value =  1.701158124176943
step =  7600 loss value =  1.563604683464585
step =  8000 loss value =  1

In [41]:
print(XOR_obj.name, "\n")

test_data = np.array([[0,0], [0,1], [1,0], [1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = XOR_obj.predict(input_data)
    print(input_data, " = ", logical_val, "\n")
    
for data in test_data:
    print(XOR_obj.predict(data))

XOR_GATE 

[0 0]  =  0 

[0 1]  =  1 

[1 0]  =  1 

[1 1]  =  0 

(array([0.10985678]), 0)
(array([0.84608213]), 1)
(array([0.81652328]), 1)
(array([0.23197848]), 0)
