In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

# 수치미분 함수
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [38]:

class LogicGate:
    
    def __init__(self, gate_name, xdata, tdata):
        
        self.name = gate_name
        
        # 입력 데이터, 정답 데이터 초기화
        self.__xdata = xdata.reshape(4, 2)
        self.__tdata = tdata.reshape(4, 1)
        
        self.__W = np.random.rand(2,1)
        self.__b = np.random.rand(1)
        
        self.__learning_rate = 1e-2
        
    def __loss_func(self):
        
        delta = 1e-7
        
        z = np.dot(self.__xdata, self.__W) + self.__b
        y = sigmoid(z)
        
        return -np.sum(self.__tdata * np.log(y + delta) + (1 - self.__tdata) * np.log((1 - y) + delta))
    
    def error_val(self):
        
        delta = 1e-7
        
        z = np.dot(self.__xdata, self.__W) + self.__b
        y = sigmoid(z)
        
        return -np.sum(self.__tdata * np.log(y + delta) + (1 - self.__tdata) * np.log((1 - y) + delta))
    
    def train(self):
        
        f = lambda x : self.__loss_func()
        
        print('Initial error value = ', self.error_val())
        
        for step in range(8001):
            
            self.__W -= self.__learning_rate * numerical_derivative(f, self.__W)
            self.__b -= self.__learning_rate * numerical_derivative(f, self.__b)
            
            if (step % 400 == 0):
                print("step = ", step, "error value = ", self.error_val())
                
    def predict(self, input_data):
        
        z = np.dot(input_data, self.__W) + self.__b
        y = sigmoid(z)
        
        if y > 0.5:
            result = 1
        else:
            result = 0
            
        return y, result

In [7]:
xdata = np.array([[0,0], [0,1], [1,0], [1,1]])
tdata = np.array([0,0,0,1])

AND_obj = LogicGate("AND_GATE", xdata, tdata)

AND_obj.train()

Initial error value =  5.410023878350042
step =  0 error value =  16.118095350958335
step =  400 error value =  16.118095350958335
step =  800 error value =  16.118095350958335
step =  1200 error value =  16.118095350958335
step =  1600 error value =  16.118095350958335
step =  2000 error value =  16.118095350958335
step =  2400 error value =  16.118095350958335
step =  2800 error value =  16.118095350958335
step =  3200 error value =  16.118095350958335
step =  3600 error value =  16.118095350958335
step =  4000 error value =  16.118095350958335
step =  4400 error value =  16.118095350958335
step =  4800 error value =  16.118095350958335
step =  5200 error value =  16.118095350958335
step =  5600 error value =  16.118095350958335
step =  6000 error value =  16.118095350958335
step =  6400 error value =  16.118095350958335
step =  6800 error value =  16.118095350958335
step =  7200 error value =  16.118095350958335
step =  7600 error value =  16.118095350958335
step =  8000 error value

In [8]:
print(AND_obj.name, "\n")

test_data = np.array([[0,0], [0,1], [1,0], [1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = AND_obj.predict(input_data)
    print(input_data, " = ", logical_val, "\n")

for data in test_data:
    print(AND_obj.predict(data))

AND_GATE 

[0 0]  =  0 

[0 1]  =  0 

[1 0]  =  0 

[1 1]  =  0 



In [12]:
xdata = np.array([[0,0], [0,1], [1,0], [1,1]])
tdata = np.array([0,1,1,1])

OR_obj = LogicGate("OR_GATE", xdata, tdata)

OR_obj.train()

Initial error value =  1.7022870618009678
step =  0 error value =  44.46269413705047
step =  400 error value =  -3.999999802335482e-07
step =  800 error value =  -3.999999802335482e-07
step =  1200 error value =  -3.999999802335482e-07
step =  1600 error value =  -3.999999802335482e-07
step =  2000 error value =  -3.999999802335482e-07
step =  2400 error value =  -3.999999802335482e-07
step =  2800 error value =  -3.999999802335482e-07
step =  3200 error value =  -3.999999802335482e-07
step =  3600 error value =  -3.999999802335482e-07
step =  4000 error value =  -3.999999802335482e-07
step =  4400 error value =  -3.999999802335482e-07
step =  4800 error value =  -3.999999802335482e-07
step =  5200 error value =  -3.999999802335482e-07
step =  5600 error value =  -3.999999802335482e-07
step =  6000 error value =  -3.999999802335482e-07
step =  6400 error value =  -3.999999802335482e-07
step =  6800 error value =  -3.999999802335482e-07
step =  7200 error value =  -3.999999802335482e-07

In [13]:
print(OR_obj.name, "\n")

test_data = np.array([[0,0], [0,1], [1,0], [1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = OR_obj.predict(input_data)
    print(input_data, " = ", logical_val, "\n")
    
for data in test_data:
    print(OR_obj.predict(data))

OR_GATE 

[0 0]  =  0 

[0 1]  =  1 

[1 0]  =  1 

[1 1]  =  1 



In [26]:
xdata = np.array([[0,0], [0,1], [1,0], [1,1]])
tdata = np.array([1,1,1,0])

NAND_obj = LogicGate("NAND_GATE", xdata, tdata)

NAND_obj.train()

Initial error value =  2.9930299720353943
step =  0 error value =  5.470951468790784e-05
step =  400 error value =  1.0203353211953775e-05
step =  800 error value =  5.52729389221318e-06
step =  1200 error value =  3.731171306909711e-06
step =  1600 error value =  2.778213374706791e-06
step =  2000 error value =  2.1865895746106875e-06
step =  2400 error value =  1.7830853451170134e-06
step =  2800 error value =  1.4900412047356776e-06
step =  3200 error value =  1.267418694063748e-06
step =  3600 error value =  1.0924680509318898e-06
step =  4000 error value =  9.512999403363998e-07
step =  4400 error value =  8.349514853778852e-07
step =  4800 error value =  7.373782204083103e-07
step =  5200 error value =  6.543546243551792e-07
step =  5600 error value =  5.82837155744423e-07
step =  6000 error value =  5.205775531258724e-07
step =  6400 error value =  4.658787359668547e-07
step =  6800 error value =  4.174354527659259e-07
step =  7200 error value =  3.742272557762605e-07
step =  76

In [27]:
print(NAND_obj.name, "\n")

test_data = np.array([[0,0], [0,1], [1,0], [1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = NAND_obj.predict(input_data)
    print(input_data, " = ", logical_val, "\n")
    
for data in test_data:
    print(NAND_obj.predict(data))

NAND_GATE 

[0 0]  =  1 

[0 1]  =  1 

[1 0]  =  1 

[1 1]  =  0 



In [28]:
xdata = np.array([[0,0], [0,1], [1,0], [1,1]])
tdata = np.array([0,1,1,0])

XOR_obj = LogicGate("XOR_GATE", xdata, tdata)

XOR_obj.train()

Initial error value =  2.863757440193667
step =  0 error value =  32.23619110191665
step =  400 error value =  32.23619110191665
step =  800 error value =  32.23619110191665
step =  1200 error value =  32.23619110191665
step =  1600 error value =  32.23619110191665
step =  2000 error value =  32.23619110191665
step =  2400 error value =  32.23619110191665
step =  2800 error value =  32.23619110191665
step =  3200 error value =  32.23619110191665
step =  3600 error value =  32.23619110191665
step =  4000 error value =  32.23619110191665
step =  4400 error value =  32.23619110191665
step =  4800 error value =  32.23619110191665
step =  5200 error value =  32.23619110191665
step =  5600 error value =  32.23619110191665
step =  6000 error value =  32.23619110191665
step =  6400 error value =  32.23619110191665
step =  6800 error value =  32.23619110191665
step =  7200 error value =  32.23619110191665
step =  7600 error value =  32.23619110191665
step =  8000 error value =  32.2361911019166

In [30]:
print(XOR_obj.name, "\n")

test_data = np.array([[0,0], [0,1], [1,0], [1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = XOR_obj.predict(input_data)
    print(input_data, " = ", logical_val, "\n")
    
for data in test_data:
    print(XOR_obj.predict(data))

XOR_GATE 

[0 0]  =  0 

[0 1]  =  0 

[1 0]  =  0 

[1 1]  =  0 

(array([8.40543338e-22]), 0)
(array([4.3219533e-34]), 0)
(array([2.44088871e-30]), 0)
(array([1.25506997e-42]), 0)


In [37]:
input_data = np.array([ [0,0], [0,1], [1,0], [1,1]])

s1 = []
s2 = []

new_input_data = []
final_output = []

for index in range(len(input_data)):
    
    s1 = NAND_obj.predict(input_data[index])
    s2 = OR_obj.predict(input_data[index])
    
    new_input_data.append(s1[-1])
    new_input_data.append(s2[-1])
    
    (sigmoid_val, logical_val) = AND_obj.predict(np.array(new_input_data))
    
    final_output.append(logical_val)
    new_input_data = []
    
for index in range(len(input_data)):
    print(input_data[index], " = ", final_output[index], end='')
    print('\n')

[0 0]  =  0

[0 1]  =  0

[1 0]  =  0

[1 1]  =  0

