In [1]:
import numpy as np

loaded_data = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[ :, 0:-1]
t_data = loaded_data[ :, [-1]]

print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)
print(x_data)
print(t_data)

x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [2]:
W = np.random.rand(3,1) # 3x1행렬
b = np.random.rand(1)
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.08942005]
 [0.30557075]
 [0.69715137]] , W.shape =  (3, 1) , b =  [0.62879307] , b.shape =  (1,)


In [3]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    
    return ( np.sum( (t-y)**2 ) ) / (len(x))

In [4]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [5]:
def error_val(x, t):
    y = np.dot(x, W) + b
    return ( np.sum( (t-y)**2 ) ) / (len(x))

In [6]:
def predict(x):
    y = np.dot(x,W) + b
    return y

In [8]:
learning_rate = 1e-5 # 발산하는 경우, 1e-3 ~ 1e-6 등으로 바꾸어서 실행

f = lambda x : loss_func(x_data, t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b)

for step in range(80001):
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if(step % 1000 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ", b)

Initial error value =  6.210244187600227 Initial W =  [[0.35849583]
 [0.52846639]
 [1.11910044]] 
 , b =  [0.61275174]
step =  0 error value =  6.210243715913572 W =  [[0.35849519]
 [0.52846622]
 [1.11910125]] , b =  [0.61274984]
step =  1000 error value =  6.209801600255022 W =  [[0.35793215]
 [0.52835183]
 [1.11978314]] , b =  [0.61084762]
step =  2000 error value =  6.20939723035184 W =  [[0.35749695]
 [0.52831977]
 [1.12026033]] , b =  [0.60894445]
step =  3000 error value =  6.209011876096497 W =  [[0.35716012]
 [0.52833179]
 [1.12059886]] , b =  [0.60704086]
step =  4000 error value =  6.208636526902013 W =  [[0.35689914]
 [0.52836529]
 [1.12084268]] , b =  [0.60513717]
step =  5000 error value =  6.208266683016396 W =  [[0.35669674]
 [0.52840728]
 [1.12102127]] , b =  [0.60323364]
step =  6000 error value =  6.207900011799547 W =  [[0.35653966]
 [0.5284506 ]
 [1.12115452]] , b =  [0.60133042]
step =  7000 error value =  6.207535261299949 W =  [[0.35641766]
 [0.52849157]
 [1.1212

In [9]:
test_data = np.array([100, 98, 81])

predict(test_data)

array([178.85314251])