In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import SGD
print(tf.__version__)

2.7.0


In [2]:
#x_data = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]).astype('float32')
x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1]).astype('float32')

In [3]:
model = tf.keras.models.Sequential()

#model.add(tf.keras.layers.Dense(8, input_shape=(1,), activation='sigmoid'))
model.add(tf.keras.layers.Flatten(input_shape=(2,)))
model.add(tf.keras.layers.Dense(8, activation='sigmoid'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [4]:
model.compile(tf.keras.optimizers.SGD(learning_rate=0.001),
             loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 16        
                                                                 
 dense_1 (Dense)             (None, 1)                 9         
                                                                 
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [5]:
hist = model.fit(x_data, t_data, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 347ms/step - loss: 0.7878 - accuracy: 0.4000
Epoch 2/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7280 - accuracy: 0.4000
Epoch 3/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6882 - accuracy: 0.4000
Epoch 4/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6633 - accuracy: 0.4000
Epoch 5/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6477 - accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6372 - accuracy: 0.7000
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6295 - accuracy: 0.8000
Epoch 8/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6235 - accuracy: 0.9000
Epoch 9/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6185 - accuracy: 0.9000
Epoch 10/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6143 - accuracy: 1.0000
Epoch 11/500
1/1 [=========

In [6]:
test_data = np.array([0.5, 3.0, 3.5, 11.0, 13.0, 31.0])

sigmoid_value = model.predict(test_data)

logical_value = tf.cast(sigmoid_value > 0.5, dtype=tf.float32)

for i in range(len(test_data)):
    print(test_data[i], 
          sigmoid_value[i], 
          logical_value.numpy()[i])

0.5 [0.03951365] [0.]
3.0 [0.04291135] [0.]
3.5 [0.04882959] [0.]
11.0 [0.39217213] [0.]
13.0 [0.5344784] [1.]
31.0 [0.90551525] [1.]


In [7]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 8) dtype=float32, numpy=
 array([[ 0.15172142, -0.16687782,  0.14053296,  1.0757422 ,  0.15875392,
          0.916049  ,  0.15217134, -0.14028825]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(8,) dtype=float32, numpy=
 array([-0.83988607,  1.1547694 , -0.58517075,  0.14864194, -0.9894956 ,
         0.08413281, -0.84967303,  0.5800329 ], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(8, 1) dtype=float32, numpy=
 array([[ 1.4694921],
        [-2.202324 ],
        [ 1.1407077],
        [-1.5367962],
        [ 1.6613387],
        [-0.8518709],
        [ 1.4833952],
        [-1.4597722]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-0.91615987], dtype=float32)>]